version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongo_db_chat
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=golovkin
      - MONGO_INITDB_ROOT_PASSWORD=golovkin

  mongo-express:
    image: mongo-express
    container_name: mongo_express_chat
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=golovkin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=golovkin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb

volumes:
  mongo: {}
